### GENERAL SETTINGS ###

# Site settings
title: GopherJS
description: "GopherJS compiles Go code to pure JavaScript. It has support for almost everything in the language and standard library, including Goroutines. Take advantage of Go's elegant type system, compile-time checks, and concurrency model to build client side applications."
baseurl: ""
url: "http://gopherjs.org"

permalink: /blog/:year/:month/:day/:title/

colors:
  primary: "#5ba642"
  secondary: "#28262C"
  tertiary: "#257394"
